version: '3.3'

services:
  node:
    image: node:alpine
    user: root
    container_name: node
    volumes:
      - ../var/www/nodejs:/app
    working_dir: /app/cheapestway
    command: npm start
    networks:
      - cheapestway-net
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ../var/www/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../var/www/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../var/www/nodejs:/var/nodejs
      - ../var/www/certbot/conf:/etc/nginx/ssl/:ro
      - ../var/www/certbot/www:/var/www/certbot/:ro
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    networks:
      - cheapestway-net
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ../var/www/certbot/conf:/etc/letsencrypt/:rw
      - ../var/www/certbot/www:/var/www/certbot/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email your-mail@mail.ru -d cheapestway.ru --agree-tos
    networks:
      - cheapestway-net

networks:
  cheapestway-net:
    driver: bridge